<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Overview.aspx.cs" Inherits="AppliedProjectDB.Overview" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        .auto-style4 {
            text-align: left;
            visibility: inherit;
            overflow: auto;
            width: 1536px;
        }
        </style>
</head>
<body style="text-align: center; font-weight: 700; font-size: xx-large">
    <form id="form1" runat="server">
        <div>
            Applied Project Website</div>
        <asp:Menu ID="Menu1" runat="server" BackColor="#F7F6F3" DynamicHorizontalOffset="2" Font-Names="Verdana" Font-Size="0.8em" ForeColor="#7C6F57" OnMenuItemClick="Menu1_MenuItemClick" Orientation="Horizontal" RenderingMode="Table" StaticSubMenuIndent="10px" Width="100%">
            <DynamicHoverStyle BackColor="#7C6F57" ForeColor="White" />
            <DynamicMenuItemStyle HorizontalPadding="5px" VerticalPadding="2px" />
            <DynamicMenuStyle BackColor="#F7F6F3" />
            <DynamicSelectedStyle BackColor="#5D7B9D" />
            <Items>
                <asp:MenuItem NavigateUrl="~/Home.aspx" Text="Home" Value="Home"></asp:MenuItem>
                <asp:MenuItem NavigateUrl="~/Showcase.aspx" Text="Showcase" Value="Showcase"></asp:MenuItem>
                <asp:MenuItem NavigateUrl="~/Overview.aspx" Text="Overview" Value="Overview"></asp:MenuItem>
            </Items>
            <StaticHoverStyle BackColor="#7C6F57" ForeColor="White" />
            <StaticMenuItemStyle HorizontalPadding="5px" VerticalPadding="2px" />
            <StaticSelectedStyle BackColor="#5D7B9D" />
        </asp:Menu>
        <div class="auto-style4" style="display: inline;">
        </div>
    </form>
    <div style="margin: 10%">
        <meta charset="utf-8" />
        <b id="docs-internal-guid-c520babd-7fff-8aae-98dd-fc214d32d0c1" style="font-weight:normal;">
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: center;margin-top:12pt;margin-bottom:12pt;">
            <span style="font-size:11pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Justin Smith, Minh Phan, Kennedy Ganda, James McHugh</span></p>
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: center;margin-top:12pt;margin-bottom:12pt;">
            <span style="font-size:11pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">TCSS 445-Winter 2020</span></p>
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: center;margin-top:12pt;margin-bottom:12pt;">
            <span style="font-size:11pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Final Report</span></p>
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: center;margin-top:0pt;margin-bottom:0pt;">
            <span style="font-size:11pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">University of Washington Tacoma</span></p>
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: center;margin-top:0pt;margin-bottom:0pt;">
            <span style="font-size:11pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;</span></p>
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: center;margin-top:0pt;margin-bottom:0pt;">
            <span style="font-size:11pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Abstract</span><span style="font-size:11pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;</span></p>
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: center;margin-top:0pt;margin-bottom:0pt;">
            <span style="font-size:11pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">WORKING ON THIS PART- Kennedy</span></p>
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;">
            <span style="font-size:11pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;&nbsp;&nbsp;<span class="Apple-tab-span" style="white-space:pre;"> </span></span><span style="font-size:11pt;font-family:Arial;color:#ff0000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">The final report should reflect the purpose, design and technical implementation of your database application. This report should be 3 - 5 pages (~2500 words), Times 11 font and single column. The report must include an abstract, introduction, objective and scope of the project, relation to other existing work that closely relate to your database application, the main body of work, an overview of the architecture, conclusions with contribution, design</span></p>
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;">
            <span style="font-size:11pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;</span></p>
        <p dir="ltr" style="line-height:1.38;text-align: center;margin-top:0pt;margin-bottom:0pt;">
            <span style="font-size:11pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;</span></p>
        <br />
        <br />
        <br />
        <p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;">
            <span style="font-size:11pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Keywords:</span></p>
        <p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;">
            <span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Part E (Final Report) ----AM WORKING ON THIS OFFLINE&nbsp; I WILL POST EACH SECTION FOR YOU GUYS TO TAKE A LOOK. ----Kennedy</span></p>
        <p dir="ltr" style="line-height:1.38;margin-left: 18pt;margin-top:0pt;margin-bottom:0pt;">
            <span style="font-size:11pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">1.0. Introduction</span></p>
        <p dir="ltr" style="line-height:1.38;margin-left: 18pt;text-align: justify;margin-top:0pt;margin-bottom:0pt;">
            <span style="font-size:11pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;</span></p>
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;">
            <span style="font-size:11pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">This project involved creating a relational database containing all the applied projects implemented by students in the Master of Science in Business Analytics program at the University of Washington Tacoma. The projects are part of their year-long internship to showcase their skills working on real world business problems in partnership with local businesses and companies.&nbsp;</span></p>
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;">
            <span style="font-size:11pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;</span></p>
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;">
            <span style="font-size:11pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Under the supervision of Milgard faculty advisors, teams of three to six students from the Master of Science in Business Analytics (MSBA) program work on important actionable projects to aid businesses or organizations. Our team is attempting to store data related to these Applied Projects from the Milgard Center for Business Analytics. We want to keep track of current ongoing applied projects, as well as those from prior years. We plan to store and update relevant information regarding each project such as contributing members, faculty advisors, involved partners, and a link to access more details on the project. We also plan to store contact information so that employers can reach out to students or faculty members involved with a specific 
            project.&nbsp;</span></p>
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;">
            <span style="font-size:11pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;">
            <span style="font-size:11pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;This report&nbsp; is organized in different parts, </span><span style="font-size:11pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Part A: </span><span style="font-size:11pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Appendix A: ER Diagram, </span>
            <span style="font-size:11pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Part B: </span><span style="font-size:11pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Appendix B: Normalization Proof to BCNF&nbsp; , </span><span style="font-size:11pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Part C: </span>
            <span style="font-size:11pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Appendix C: Relational Schema Diagram&nbsp; , </span><span style="font-size:11pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Part E : </span><span style="font-size:11pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Appendix D: Screenshots of functional SQL Queries&nbsp; and </span>
            <span style="font-size:11pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Part D: </span><span style="font-size:11pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Appendix E: Screenshots of functional Web Interface.</span></p>
        <p dir="ltr" style="line-height:1.38;margin-left: 18pt;margin-top:12pt;margin-bottom:12pt;">
            <span style="font-size:11pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">2.0. Goal &amp; Scope</span></p>
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;">
            <span style="font-size:11pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">The main goal of this project was to streamline access to MSBA Applied Projects. Creating a database will allow multiple authorized users to gain access to information regarding these projects and cater their search to what they want to see. It will also allow people to see what projects are currently being worked on by students and past projects that had been implemented in a single repository.</span></p>
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;">
            <span style="font-size:11pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;</span></p>
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;">
            <span style="font-size:11pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;&nbsp;<span class="Apple-tab-span" style="white-space:pre;"> </span>This database will grant employers, students and Companies interested in the applied project partnership, easier access to the applied projects the students have worked on. The database will also allow MSBA students to showcase their projects to potential employers, by having different views without compromising the integrity of the data.&nbsp;&nbsp;</span></p>
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;">
            <span style="font-size:11pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;&nbsp;&nbsp;&nbsp;<span class="Apple-tab-span" style="white-space:pre;"> </span>Employers will also be able to filter their results in such a way to find applied projects relevant to what they are looking for. If there were projects that caught their interest, they could specific people involved in the project.&nbsp; This would make the database a valuable resource to find future job candidates.&nbsp;</span></p>
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;">
            <span style="font-size:11pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;</span></p>
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;">
            <span style="font-size:11pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Another motivation for the idea is the maintenance.&nbsp; Without having a proper database, the data management system contains multiple files which lead to duplicate data. Creating a database helps us deal with data redundancy better. All the data appears consistently across the database, so any change made to the database that will update immediately to all the users. It is extremely necessary to ensure that the data is correct and consistent for all the users, then make the system a lot more maintainable.</span></p>
        <p dir="ltr" style="line-height:1.38;margin-top:12pt;margin-bottom:12pt;">
            <span style="font-size:11pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;&nbsp;2.1. Specific Objectives:</span></p>
        <p dir="ltr" style="line-height:1.7999999999999998;margin-top:12pt;margin-bottom:12pt;">
            <span style="font-size:11pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;a. Create a single repository for all MSBA applied projects, for easier access and maintenance</span></p>
        <p dir="ltr" style="line-height:1.7999999999999998;margin-top:12pt;margin-bottom:12pt;">
            <span style="font-size:11pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;b. Create a platform to enable both students and potential employers to have different views of the projects based on their needs, without compromising security and integrity.</span></p>
        <p dir="ltr" style="line-height:1.38;margin-top:12pt;margin-bottom:12pt;">
            <span style="font-size:11pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;</span></p>
        <p dir="ltr" style="line-height:1.38;margin-left: 18pt;margin-top:12pt;margin-bottom:12pt;">
            <span style="font-size:11pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">3.0. Literature Review / Methodology&nbsp;</span></p>
        <p dir="ltr" style="line-height:1.38;text-align: justify;margin-top:0pt;margin-bottom:0pt;">
            <span style="font-size:11pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3.1. Existing Solutions</span></p>
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;">
            <span style="font-size:11pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="Apple-tab-span" style="white-space:pre;"> </span>Currently the existing solutions for the business problems are paid services which requires monthly subscriptions e.g. Salesforce, Azure SQL Server-Database. Our solution will be different because it will allow us the autonomy to design our own database schema based on our needs and will help cost reduction cutting down the monthly subscription. All the Applied Projects from the MSBA program are accessed from the university&#39;s website, with minimal information available about the projects themselves as well as the participants. We have also found that many of the links to various projects have been either taken down or no longer work. With our database solution, all the related 
            information pertaining to each project would be easily accessible and kept in one central place.&nbsp;</span></p>
        <p dir="ltr" style="line-height:1.38;text-align: justify;margin-top:0pt;margin-bottom:0pt;">
            <span style="font-size:11pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;</span></p>
        <p dir="ltr" style="line-height:1.38;margin-left: 54pt;text-align: justify;margin-top:0pt;margin-bottom:0pt;">
            <span style="font-size:11pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">3.2. Methodology:</span></p>
        <p dir="ltr" style="line-height:1.38;text-align: justify;margin-top:0pt;margin-bottom:0pt;">
            <span style="font-size:11pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;</span></p>
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;">
            <span style="font-size:11pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">This project was implemented in three phases, phase I involved writing a project proposal with a brief description of the project. In this phase, we collected the relevant information to come up with&nbsp;&nbsp; a list of objects to be used in the conceptual design, i.e. entity names, attributes etc. Phase two of the project involved creating a logical design of the database, we created a database schema containing various relations, attributes and tuples in each relation and the corresponding relationships between various relations. Phase three of the project involved, creating an Entity-Relation (ER-diagram) and redesigning the existing database schema based on the ER-diagram.</span></p>
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;">
            <span style="font-size:11pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;</span></p>
        <p dir="ltr" style="line-height:1.7999999999999998;margin-top:0pt;margin-bottom:0pt;">
            <span style="font-size:11pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;&nbsp;&nbsp;<span class="Apple-tab-span" style="white-space:pre;"> </span>In the implementation of the project, we used relational database model. The main motivation for using this model was due to the nature of the data and the advantages that relational model offers e.g. program data independence, concurrency, security, integrity among others. Some of the tools and applications we used in different steps were, SQL live for interactive interface for writing queries, Visual Studio, MySQL, ASP.NET.&nbsp; Phase three also involved creating a web interface for running queries and accessing the database.</span></p>
        </b>
        <br class="Apple-interchange-newline" />
    </div>
</body>
</html>
